'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class BirthdayClubMemberInfo
    Protected WithEvents Head1 As System.Web.UI.HtmlControls.HtmlHead
    Protected WithEvents form1 As System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents lblMessage As System.Web.UI.WebControls.Label
    Protected WithEvents lclChooseLanguage As System.Web.UI.WebControls.Localize
    Protected WithEvents ddlLanguages As System.Web.UI.WebControls.DropDownList
    Protected WithEvents lclInstructions As System.Web.UI.WebControls.Localize
    Protected WithEvents lclYourName As System.Web.UI.WebControls.Localize
    Protected WithEvents txtMemberName As System.Web.UI.WebControls.TextBox
    Protected WithEvents lclYourNextBirthday As System.Web.UI.WebControls.Localize
    Protected WithEvents lblBirthdate As System.Web.UI.WebControls.Label
    Protected WithEvents calBirthDatePicker As System.Web.UI.WebControls.Calendar
    Protected WithEvents btnAdd As System.Web.UI.WebControls.Button
    Protected WithEvents lclBirthdayClubSchedule As System.Web.UI.WebControls.Localize
    Protected WithEvents calBirthDateSchedule As System.Web.UI.WebControls.Calendar
End Class
